AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  poja-sam-version-router

Globals:
  Function:
    Timeout: 900

    Tracing: Active
  Api:
    TracingEnabled: true

Parameters:
  Env:
    Type: String

Resources:
  PojaSamVersionRouterApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      BinaryMediaTypes:
        - "*~1*"

  PojaSamVersionRouterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: poja_sam_router/

      Handler: app.lambda_handler

      Runtime: python3.11

      MemorySize: 1024

      Architectures:
      - arm64

      VpcConfig:
        SecurityGroupIds:
          - !Sub '{{resolve:ssm:/jcloudify-api/sg/id}}'
        SubnetIds:
          - !Sub '{{resolve:ssm:/jcloudify-api/private/subnet1/id}}'
          - !Sub '{{resolve:ssm:/jcloudify-api/private/subnet2/id}}'

      Events:
        Gen:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId:
              Ref: PojaSamVersionRouterApi

      Role: !Sub '{{resolve:ssm:/jcloudify-api/${Env}/execution/role-arn}}'

      Environment:
        Variables:
          POJA_SAM_API_KEY: !Sub '{{resolve:ssm:/jcloudify-api/${Env}/poja/sam/api/key}}'

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

Outputs:
  PojaSamVersionRouterApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${PojaSamVersionRouterApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  PojaSamVersionRouterFunction:
    Description: Poja Sam Version Router Lambda Function ARN
    Value: !GetAtt PojaSamVersionRouterFunction.Arn
